--------------------------------------------------------
--  File created - Friday-June-06-2025   
--------------------------------------------------------
DROP TABLE "CarrLoanLASum" cascade constraints;
DROP TABLE "CarrLoanWorkingThree" cascade constraints;
DROP PROCEDURE "CARRLOANWORKINGSUMMARY_TWO";
--------------------------------------------------------
--  DDL for Table CarrLoanLASum
--------------------------------------------------------

  CREATE TABLE "CarrLoanLASum" 
   (	"Id" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"WebBasedReturnCode" NVARCHAR2(700), 
	"SumOfAmountCreditRisk" NUMBER(30,2), 
	"SumOfRWA" NUMBER(30,2), 
	"SumOfTotalImpairment" NUMBER(30,2), 
	"CreatedBy" NVARCHAR2(150), 
	"CreatedAt" TIMESTAMP (7), 
	"ModifiedBy" NVARCHAR2(150), 
	"ModifiedAt" TIMESTAMP (7)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CarrLoanWorkingThree
--------------------------------------------------------

  CREATE TABLE "CarrLoanWorkingThree" 
   (	"Id" NUMBER(10,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"AccountNumber" NVARCHAR2(225), 
	"CustomerId" NVARCHAR2(225), 
	"AccountName" NVARCHAR2(750), 
	"LoanNoteProduct" NVARCHAR2(150), 
	"AccountCurrencyCode" NVARCHAR2(5), 
	"Stage" NVARCHAR2(50), 
	"TotalImpairment" NUMBER(18,2), 
	"CustConstitutionCode" NVARCHAR2(50), 
	"SchmCode" NVARCHAR2(50), 
	"CapitalAdqDesc" NVARCHAR2(100), 
	"SecurityValue" NUMBER(20,2), 
	"ExpiryDate" TIMESTAMP (7), 
	"ReportingDate" TIMESTAMP (7), 
	"RemainingMaturityDays" NUMBER(10,0), 
	"FinancialInstitutions" NVARCHAR2(150), 
	"NPAResidential" NVARCHAR2(150), 
	"ProvisionCover" NUMBER(20,2), 
	"LTV" NUMBER(20,2), 
	"RetailCash" NVARCHAR2(150), 
	"Category" NVARCHAR2(150), 
	"AmtconsideredforCdtRisk" NUMBER(20,2), 
	"RiskRating" NVARCHAR2(2000), 
	"RiskWeight" NUMBER(20,2), 
	"CBSLCode" NVARCHAR2(255), 
	"CRMCode" NVARCHAR2(255), 
	"RWA" NUMBER(20,2), 
	"IsExcluded" NUMBER(10,0), 
	"CreatedBy" NVARCHAR2(150), 
	"CreatedAt" TIMESTAMP (7), 
	"ModifiedBy" NVARCHAR2(150), 
	"ModifiedAt" TIMESTAMP (7)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CarrLoanLASum
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CarrLoanLASum" ON "CarrLoanLASum" ("Id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CarrLoanWorkingThree
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CarrLoanWorkingThree" ON "CarrLoanWorkingThree" ("Id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure CARRLOANWORKINGSUMMARY_TWO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "CARRLOANWORKINGSUMMARY_TWO" (
  p_createduser IN VARCHAR2
) AS
BEGIN
  -- 0)  Wipe out any prior data
  EXECUTE IMMEDIATE 'TRUNCATE TABLE "CarrLoanLASum"';

  -- 1)  Insert all _not_ excluded, grouped by CBSLCode

  INSERT INTO "CarrLoanLASum" (
    "WebBasedReturnCode",
    "SumOfAmountCreditRisk",
    "SumOfRWA",
    "SumOfTotalImpairment"
  )
  SELECT
    "CBSLCode"                                 AS "WebBasedReturnCode",
    SUM("AmtconsideredforCdtRisk")             AS "SumOfAmountCreditRisk",
    SUM("RWA")                                  AS "SumOfRWA",
    SUM("TotalImpairment")                      AS "SumOfTotalImpairment"
  FROM "CarrLoanWorkingThree"
  WHERE "IsExcluded" = 0
  GROUP BY "CBSLCode";

  COMMIT;

  -- 2)  Insert single ?Excluded Accounts? row

  INSERT INTO "CarrLoanLASum" (
    "WebBasedReturnCode",
    "SumOfAmountCreditRisk",
    "SumOfRWA",
    "SumOfTotalImpairment"
  )
  SELECT
    'Excluded Accounts'                       AS "WebBasedReturnCode",
    SUM("AmtconsideredforCdtRisk")              AS "SumOfAmountCreditRisk",
    SUM("RWA")                                  AS "SumOfRWA",
    SUM("TotalImpairment")                      AS "SumOfTotalImpairment"
  FROM "CarrLoanWorkingThree"
  WHERE "IsExcluded" = 1;

  COMMIT;

  -- 3)  Now update those newly-inserted rows to stamp in user & time

  UPDATE "CarrLoanLASum"
     SET "CreatedBy" = p_createduser,
         "CreatedAt" = SYSTIMESTAMP
   WHERE "CreatedBy" IS NULL;
   COMMIT;

END;

/
--------------------------------------------------------
--  Constraints for Table CarrLoanLASum
--------------------------------------------------------

  ALTER TABLE "CarrLoanLASum" MODIFY ("WebBasedReturnCode" NOT NULL ENABLE);
  ALTER TABLE "CarrLoanLASum" ADD CONSTRAINT "PK_CarrLoanLASum" PRIMARY KEY ("Id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CarrLoanLASum" MODIFY ("Id" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CarrLoanWorkingThree
--------------------------------------------------------

  ALTER TABLE "CarrLoanWorkingThree" MODIFY ("AccountNumber" NOT NULL ENABLE);
  ALTER TABLE "CarrLoanWorkingThree" MODIFY ("CustomerId" NOT NULL ENABLE);
  ALTER TABLE "CarrLoanWorkingThree" MODIFY ("AccountName" NOT NULL ENABLE);
  ALTER TABLE "CarrLoanWorkingThree" MODIFY ("LoanNoteProduct" NOT NULL ENABLE);
  ALTER TABLE "CarrLoanWorkingThree" MODIFY ("Stage" NOT NULL ENABLE);
  ALTER TABLE "CarrLoanWorkingThree" ADD CONSTRAINT "PK_CarrLoanWorkingThree" PRIMARY KEY ("Id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CarrLoanWorkingThree" MODIFY ("Id" NOT NULL ENABLE);
